server:
  port: 8080
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: 'jdbc:h2:mem:net-tester-db'
    driver-class-name: org.h2.Driver
    username: admin
    password: 
  data:
    rest:
        basePath: /api
